-- Insert unique countries into Countries table
INSERT INTO Countries (name) VALUES ('Afghanistan');
INSERT INTO Countries (name) VALUES ('Albania');
INSERT INTO Countries (name) VALUES ('Algeria');
INSERT INTO Countries (name) VALUES ('Angola');
INSERT INTO Countries (name) VALUES ('Antigua and Barbuda');
INSERT INTO Countries (name) VALUES ('Argentina');
INSERT INTO Countries (name) VALUES ('Armenia');
INSERT INTO Countries (name) VALUES ('Australia');
INSERT INTO Countries (name) VALUES ('Austria');
INSERT INTO Countries (name) VALUES ('Azerbaijan');
INSERT INTO Countries (name) VALUES ('Bahamas');
INSERT INTO Countries (name) VALUES ('Bahrain');
INSERT INTO Countries (name) VALUES ('Bangladesh');
INSERT INTO Countries (name) VALUES ('Barbados');
INSERT INTO Countries (name) VALUES ('Belarus');
INSERT INTO Countries (name) VALUES ('Belgium');
INSERT INTO Countries (name) VALUES ('Belize');
INSERT INTO Countries (name) VALUES ('Benin');
INSERT INTO Countries (name) VALUES ('Bhutan');
INSERT INTO Countries (name) VALUES ('Bolivia');
INSERT INTO Countries (name) VALUES ('Bosnia and Herzegovina');
INSERT INTO Countries (name) VALUES ('Botswana');
INSERT INTO Countries (name) VALUES ('Brazil');
INSERT INTO Countries (name) VALUES ('Brunei');
INSERT INTO Countries (name) VALUES ('Bulgaria');
INSERT INTO Countries (name) VALUES ('Burkina Faso');
INSERT INTO Countries (name) VALUES ('Burundi');
INSERT INTO Countries (name) VALUES ('Cabo Verde');
INSERT INTO Countries (name) VALUES ('Cambodia');
INSERT INTO Countries (name) VALUES ('Cameroon');
INSERT INTO Countries (name) VALUES ('Canada');
INSERT INTO Countries (name) VALUES ('Central African Republic');
INSERT INTO Countries (name) VALUES ('Chad');
INSERT INTO Countries (name) VALUES ('Chile');
INSERT INTO Countries (name) VALUES ('China');
INSERT INTO Countries (name) VALUES ('Colombia');
INSERT INTO Countries (name) VALUES ('Comoros');
INSERT INTO Countries (name) VALUES ('Congo');
INSERT INTO Countries (name) VALUES ('Costa Rica');
INSERT INTO Countries (name) VALUES ('Croatia');
INSERT INTO Countries (name) VALUES ('Cuba');
INSERT INTO Countries (name) VALUES ('Cyprus');
INSERT INTO Countries (name) VALUES ('Czech Republic');
INSERT INTO Countries (name) VALUES ('Côte d’Ivoire');
INSERT INTO Countries (name) VALUES ('Democratic Republic of the Congo');
INSERT INTO Countries (name) VALUES ('Denmark');
INSERT INTO Countries (name) VALUES ('Djibouti');
INSERT INTO Countries (name) VALUES ('Dominican Republic');
INSERT INTO Countries (name) VALUES ('Ecuador');
INSERT INTO Countries (name) VALUES ('Egypt');
INSERT INTO Countries (name) VALUES ('El Salvador');
INSERT INTO Countries (name) VALUES ('Equatorial Guinea');
INSERT INTO Countries (name) VALUES ('Eritrea');
INSERT INTO Countries (name) VALUES ('Estonia');
INSERT INTO Countries (name) VALUES ('Eswatini');
INSERT INTO Countries (name) VALUES ('Ethiopia');
INSERT INTO Countries (name) VALUES ('Fiji');
INSERT INTO Countries (name) VALUES ('Finland');
INSERT INTO Countries (name) VALUES ('France');
INSERT INTO Countries (name) VALUES ('Gabon');
INSERT INTO Countries (name) VALUES ('Gambia');
INSERT INTO Countries (name) VALUES ('Georgia');
INSERT INTO Countries (name) VALUES ('Germany');
INSERT INTO Countries (name) VALUES ('Ghana');
INSERT INTO Countries (name) VALUES ('Greece');
INSERT INTO Countries (name) VALUES ('Grenada');
INSERT INTO Countries (name) VALUES ('Guatemala');
INSERT INTO Countries (name) VALUES ('Guinea');
INSERT INTO Countries (name) VALUES ('Guinea-Bissau');
INSERT INTO Countries (name) VALUES ('Guyana');
INSERT INTO Countries (name) VALUES ('Haiti');
INSERT INTO Countries (name) VALUES ('Honduras');
INSERT INTO Countries (name) VALUES ('Hungary');
INSERT INTO Countries (name) VALUES ('Iceland');
INSERT INTO Countries (name) VALUES ('India');
INSERT INTO Countries (name) VALUES ('Indonesia');
INSERT INTO Countries (name) VALUES ('Iran');
INSERT INTO Countries (name) VALUES ('Iraq');
INSERT INTO Countries (name) VALUES ('Ireland');
INSERT INTO Countries (name) VALUES ('Israel');
INSERT INTO Countries (name) VALUES ('Italy');
INSERT INTO Countries (name) VALUES ('Jamaica');
INSERT INTO Countries (name) VALUES ('Japan');
INSERT INTO Countries (name) VALUES ('Jordan');
INSERT INTO Countries (name) VALUES ('Kazakhstan');
INSERT INTO Countries (name) VALUES ('Kenya');
INSERT INTO Countries (name) VALUES ('Kiribati');
INSERT INTO Countries (name) VALUES ('Kuwait');
INSERT INTO Countries (name) VALUES ('Kyrgyz Republic');
INSERT INTO Countries (name) VALUES ('Laos');
INSERT INTO Countries (name) VALUES ('Latvia');
INSERT INTO Countries (name) VALUES ('Lebanon');
INSERT INTO Countries (name) VALUES ('Lesotho');
INSERT INTO Countries (name) VALUES ('Liberia');
INSERT INTO Countries (name) VALUES ('Libya');
INSERT INTO Countries (name) VALUES ('Lithuania');
INSERT INTO Countries (name) VALUES ('Luxembourg');
INSERT INTO Countries (name) VALUES ('Madagascar');
INSERT INTO Countries (name) VALUES ('Malawi');
INSERT INTO Countries (name) VALUES ('Malaysia');
INSERT INTO Countries (name) VALUES ('Maldives');
INSERT INTO Countries (name) VALUES ('Mali');
INSERT INTO Countries (name) VALUES ('Malta');
INSERT INTO Countries (name) VALUES ('Mauritania');
INSERT INTO Countries (name) VALUES ('Mauritius');
INSERT INTO Countries (name) VALUES ('Mexico');
INSERT INTO Countries (name) VALUES ('Micronesia');
INSERT INTO Countries (name) VALUES ('Moldova');
INSERT INTO Countries (name) VALUES ('Mongolia');
INSERT INTO Countries (name) VALUES ('Montenegro');
INSERT INTO Countries (name) VALUES ('Morocco');
INSERT INTO Countries (name) VALUES ('Mozambique');
INSERT INTO Countries (name) VALUES ('Myanmar');
INSERT INTO Countries (name) VALUES ('Namibia');
INSERT INTO Countries (name) VALUES ('Nepal');
INSERT INTO Countries (name) VALUES ('Netherlands');
INSERT INTO Countries (name) VALUES ('New Zealand');
INSERT INTO Countries (name) VALUES ('Nicaragua');
INSERT INTO Countries (name) VALUES ('Niger');
INSERT INTO Countries (name) VALUES ('Nigeria');
INSERT INTO Countries (name) VALUES ('North Korea');
INSERT INTO Countries (name) VALUES ('North Macedonia');
INSERT INTO Countries (name) VALUES ('Norway');
INSERT INTO Countries (name) VALUES ('Oman');
INSERT INTO Countries (name) VALUES ('Pakistan');
INSERT INTO Countries (name) VALUES ('Palestine');
INSERT INTO Countries (name) VALUES ('Panama');
INSERT INTO Countries (name) VALUES ('Papua New Guinea');
INSERT INTO Countries (name) VALUES ('Paraguay');
INSERT INTO Countries (name) VALUES ('Peru');
INSERT INTO Countries (name) VALUES ('Philippines');
INSERT INTO Countries (name) VALUES ('Poland');
INSERT INTO Countries (name) VALUES ('Polynesia');
INSERT INTO Countries (name) VALUES ('Portugal');
INSERT INTO Countries (name) VALUES ('Qatar');
INSERT INTO Countries (name) VALUES ('Romania');
INSERT INTO Countries (name) VALUES ('Russia');
INSERT INTO Countries (name) VALUES ('Rwanda');
INSERT INTO Countries (name) VALUES ('Samoa');
INSERT INTO Countries (name) VALUES ('Sao Tome and Principe');
INSERT INTO Countries (name) VALUES ('Saudi Arabia');
INSERT INTO Countries (name) VALUES ('Senegal');
INSERT INTO Countries (name) VALUES ('Serbia');
INSERT INTO Countries (name) VALUES ('Seychelles');
INSERT INTO Countries (name) VALUES ('Sierra Leone');
INSERT INTO Countries (name) VALUES ('Singapore');
INSERT INTO Countries (name) VALUES ('Slovakia');
INSERT INTO Countries (name) VALUES ('Slovenia');
INSERT INTO Countries (name) VALUES ('Solomon Islands');
INSERT INTO Countries (name) VALUES ('Somalia');
INSERT INTO Countries (name) VALUES ('South Africa');
INSERT INTO Countries (name) VALUES ('South Korea');
INSERT INTO Countries (name) VALUES ('South Sudan');
INSERT INTO Countries (name) VALUES ('Spain');
INSERT INTO Countries (name) VALUES ('Sri Lanka');
INSERT INTO Countries (name) VALUES ('St. Lucia');
INSERT INTO Countries (name) VALUES ('St. Vincent and the Grenadines');
INSERT INTO Countries (name) VALUES ('Sudan');
INSERT INTO Countries (name) VALUES ('Suriname');
INSERT INTO Countries (name) VALUES ('Sweden');
INSERT INTO Countries (name) VALUES ('Switzerland');
INSERT INTO Countries (name) VALUES ('Syria');
INSERT INTO Countries (name) VALUES ('Tajikistan');
INSERT INTO Countries (name) VALUES ('Tanzania');
INSERT INTO Countries (name) VALUES ('Thailand');
INSERT INTO Countries (name) VALUES ('Timor-Leste');
INSERT INTO Countries (name) VALUES ('Togo');
INSERT INTO Countries (name) VALUES ('Tonga');
INSERT INTO Countries (name) VALUES ('Trinidad and Tobago');
INSERT INTO Countries (name) VALUES ('Tunisia');
INSERT INTO Countries (name) VALUES ('Turkey');
INSERT INTO Countries (name) VALUES ('Turkmenistan');
INSERT INTO Countries (name) VALUES ('Uganda');
INSERT INTO Countries (name) VALUES ('Ukraine');
INSERT INTO Countries (name) VALUES ('United Arab Emirates');
INSERT INTO Countries (name) VALUES ('United Kingdom');
INSERT INTO Countries (name) VALUES ('United States of America');
INSERT INTO Countries (name) VALUES ('Uruguay');
INSERT INTO Countries (name) VALUES ('Uzbekistan');
INSERT INTO Countries (name) VALUES ('Vanuatu');
INSERT INTO Countries (name) VALUES ('Venezuela');
INSERT INTO Countries (name) VALUES ('Vietnam');
INSERT INTO Countries (name) VALUES ('Yemen');
INSERT INTO Countries (name) VALUES ('Zambia');
INSERT INTO Countries (name) VALUES ('Zimbabwe');


-- Insert UN Data
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Afghanistan'), 8.6, 60);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Albania'), 7.2, 77);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Algeria'), 5.1, 74);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Angola'), 14.2, 52);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Antigua and Barbuda'), 6.2, 76);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Argentina'), 7.6, 76);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Armenia'), 9.0, 74);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Australia'), 6.7, 82);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Austria'), 9.4, 81);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Azerbaijan'), 7.0, 71);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Bahamas'), 6.0, 75);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Bahrain'), 2.3, 76);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Bangladesh'), 5.5, 71);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Barbados'), 10.5, 75);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Belarus'), 14.2, 71);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Belgium'), 9.8, 81);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Belize'), 5.6, 70);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Benin'), 9.6, 59);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Bhutan'), 6.3, 69);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Bolivia'), 7.6, 68);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Bosnia and Herzegovina'), 10.3, 76);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Botswana'), 7.5, 64);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Brazil'), 6.1, 74);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Brunei'), 3.0, 78);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Bulgaria'), 15.1, 74);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Burkina Faso'), 10.0, 58);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Burundi'), 11.7, 56);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Cabo Verde'), 5.5, 73);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Cambodia'), 6.3, 68);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Cameroon'), 11.9, 55);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Canada'), 7.3, 82);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Central African Republic'), 15.2, 50);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Chad'), 14.5, 51);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Chile'), 5.1, 81);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'China'), 7.0, 75);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Colombia'), 5.8, 74);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Comoros'), 7.7, 63);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Congo'), 9.0, 61);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Costa Rica'), 4.7, 79);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Côte d’Ivoire'), 13.9, 51);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Croatia'), 12.4, 77);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Cuba'), 7.7, 79);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Cyprus'), 6.8, 80);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Czech Republic'), 10.1, 78);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Democratic Republic of the Congo'), 10.7, 58);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Denmark'), 9.7, 80);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Djibouti'), 8.7, 62);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Dominican Republic'), 6.0, 73);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Ecuador'), 5.2, 76);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Egypt'), 6.2, 71);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'El Salvador'), 6.7, 73);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Equatorial Guinea'), 11.0, 57);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Eritrea'), 6.9, 63);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Estonia'), 11.9, 77);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Eswatini'), 14.1, 49);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Ethiopia'), 7.8, 63);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Fiji'), 6.8, 70);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Finland'), 9.6, 81);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'France'), 8.9, 82);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Gabon'), 9.0, 64);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Gambia'), 9.0, 60);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Georgia'), 11.5, 75);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Germany'), 10.8, 81);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Ghana'), 9.2, 61);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Greece'), 10.5, 81);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Grenada'), 7.2, 73);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Guatemala'), 5.4, 71);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Guinea'), 10.4, 58);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Guinea-Bissau'), 12.4, 55);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Guyana'), 8.0, 66);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Haiti'), 8.9, 62);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Honduras'), 5.0, 73);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Hungary'), 13.2, 75);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Iceland'), 6.3, 82);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'India'), 7.4, 67);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Indonesia'), 7.2, 69);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Iran'), 4.7, 75);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Iraq'), 5.3, 69);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Ireland'), 6.4, 81);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Israel'), 5.3, 82);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Italy'), 9.7, 83);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Jamaica'), 6.8, 75);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Japan'), 10.0, 83);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Jordan'), 3.9, 74);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Kazakhstan'), 8.9, 69);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Kenya'), 8.7, 61);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Kiribati'), 7.1, 66);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Kuwait'), 2.5, 74);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Kyrgyz Republic'), 6.4, 70);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Laos'), 7.0, 66);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Latvia'), 14.5, 74);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Lebanon'), 4.6, 79);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Lesotho'), 14.9, 50);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Liberia'), 9.0, 60);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Libya'), 5.3, 71);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Lithuania'), 15.2, 73);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Luxembourg'), 7.4, 81);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Madagascar'), 6.9, 65);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Malawi'), 8.6, 61);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Malaysia'), 4.8, 74);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Maldives'), 3.8, 76);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Mali'), 11.0, 57);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Malta'), 8.8, 80);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Mauritania'), 8.1, 63);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Mauritius'), 7.3, 74);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Mexico'), 4.8, 76);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Micronesia'), 6.2, 69);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Moldova'), 11.2, 71);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Mongolia'), 6.2, 69);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Montenegro'), 9.9, 76);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Morocco'), 5.7, 74);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Mozambique'), 11.8, 55);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Myanmar'), 8.3, 66);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Namibia'), 7.3, 64);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Nepal'), 6.5, 69);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Netherlands'), 8.4, 81);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'New Zealand'), 6.8, 82);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Nicaragua'), 4.8, 74);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Niger'), 9.6, 61);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Nigeria'), 13.3, 52);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'North Korea'), 9.2, 70);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'North Macedonia'), 9.2, 75);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Norway'), 8.4, 81);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Oman'), 2.7, 76);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Pakistan'), 7.5, 66);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Palestine'), 3.6, 73);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Panama'), 5.0, 77);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Papua New Guinea'), 7.7, 62);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Paraguay'), 5.6, 73);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Peru'), 5.6, 74);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Philippines'), 6.7, 68);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Poland'), 9.8, 77);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Polynesia'), 5.6, 74);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Portugal'), 10.3, 81);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Qatar'), 1.5, 78);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Romania'), 12.9, 74);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Russia'), 13.9, 70);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Rwanda'), 7.5, 63);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Samoa'), 5.4, 73);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Sao Tome and Principe'), 7.1, 66);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Saudi Arabia'), 3.4, 74);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Senegal'), 6.6, 66);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Serbia'), 12.7, 75);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Seychelles'), 7.6, 73);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Sierra Leone'), 14.1, 50);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Singapore'), 4.5, 83);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Slovakia'), 9.8, 76);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Slovenia'), 9.4, 80);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Solomon Islands'), 5.9, 68);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Somalia'), 12.4, 55);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'South Africa'), 12.5, 57);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'South Korea'), 5.5, 81);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'South Sudan'), 12.0, 55);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Spain'), 8.8, 82);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Sri Lanka'), 6.7, 75);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'St. Lucia'), 7.2, 75);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'St. Vincent and the Grenadines'), 7.0, 73);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Sudan'), 7.9, 63);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Suriname'), 7.3, 71);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Sweden'), 9.4, 82);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Switzerland'), 8.1, 83);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Syria'), 5.6, 70);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Tajikistan'), 5.7, 69);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Tanzania'), 7.3, 64);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Thailand'), 7.7, 74);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Timor-Leste'), 7.0, 68);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Togo'), 9.3, 59);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Tonga'), 6.1, 73);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Trinidad and Tobago'), 9.2, 70);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Tunisia'), 6.6, 75);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Turkey'), 5.7, 75);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Turkmenistan'), 7.8, 65);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Uganda'), 10.2, 57);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Ukraine'), 15.3, 71);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'United Arab Emirates'), 1.5, 77);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'United Kingdom'), 9.2, 80);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'United States of America'), 8.2, 79);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Uruguay'), 9.3, 77);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Uzbekistan'), 7.0, 68);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Vanuatu'), 4.8, 71);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Venezuela'), 5.5, 74);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Vietnam'), 5.8, 76);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Yemen'), 7.1, 64);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Zambia'), 9.7, 59);
INSERT INTO UN_Data (country_id, crude_death_rate, life_expectancy) VALUES ((SELECT country_id FROM Countries WHERE name = 'Zimbabwe'), 11.1, 55);


-- Insert World Bank Data
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Afghanistan'), 60.05854034, 565.569730408751, 64, 8.26, 24.803);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Albania'), 255.35635376, 3952.80357364813, 99, 56.9, 57.434);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Algeria'), 292.275177, 4685.05902729002, 95, 38.2, 70.848);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Angola'), 107.64356232, 3213.90261080059, 59, 22.0, 63.446);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Antigua and Barbuda'), 784.64538574, 16080.6580495874, 99, 70.0, 25.0);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Argentina'), 1525.05310059, 13679.6264980954, 94, 68.0431, 91.503);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Armenia'), 371.0, 3512.39350276709, 94, 59.1008, 63.085);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Australia'), 5322.97119141, 56739.0265346593, 93, 84.5605, 85.701);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Austria'), 4613.0, 43915.228020857, 93, 83.9401, 57.715);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Azerbaijan'), 234.0, 5500.50364628486, 96, 77.0, 54.714);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Bahamas'), 1558.79882813, 30289.4022514831, 95, 78.0, 82.746);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Bahrain'), 1134.46166992, 23734.0551143019, 98, 93.4783, 88.999);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Bangladesh'), 33.53680038, 1224.38647668165, 98, 12.9, 34.308);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Barbados'), 1158.39306641, 18954.2913724506, 97, 72.0, 31.249);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Belarus'), 353.0, 5967.06856034227, 99, 62.2304, 77.181);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Belgium'), 4442.40136719, 40893.804537772, 99, 85.0529, 97.876);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Belize'), 285.84985352, 6154.49593498217, 94, 41.59, 45.406);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Benin'), 28.41767883, 1002.41886882564, 74, 11.255, 45.695);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Bhutan'), 96.52057648, 2954.04081973327, 99, 39.8, 38.678);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Bolivia'), 194.92401123, 2996.01289804214, 89, 37.4868, 68.393);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Bosnia and Herzegovina'), 430.0, 4662.25883724069, 82, 52.6, 47.173);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Botswana'), 358.22320557, 6141.20394726616, 95, 37.3121, 67.155);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Brazil'), 782.52294922, 8936.19661756825, 96, 58.328, 85.77);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Brunei'), 732.39416504, 30625.128732694, 99, 71.2, 76.663);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Bulgaria'), 521.0, 7078.86032298969, 91, 56.6563, 73.99);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Burkina Faso'), 32.44025803, 630.124750752312, 91, 6.55, 27.53);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Burundi'), 18.2036705, 280.966831311923, 94, 2.0, 12.078);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Cabo Verde'), 139.48536682, 3415.06266730931, 93, 42.683, 64.3);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Cambodia'), 72.51950836, 1547.32010444394, 91, 6.43319, 22.188);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Cameroon'), 50.31904221, 1415.00009710569, 76, 18.3, 54.578);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Canada'), 4677.83007813, 43594.1941045394, 91, 90.0, 81.259);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Central African Republic'), 17.71483231, 366.322853938121, 43, 2.9, 40.277);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Chad'), 35.03440857, 747.588448455507, 42, 3.5, 22.515);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Chile'), 1133.27978516, 13433.9202985339, 96, 76.6296, 87.36);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'China'), 393.77990723, 8016.44559489999, 99, 50.3, 55.5);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Colombia'), 468.60543823, 6248.51490534512, 91, 55.905, 79.764);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Comoros'), 60.86703491, 1329.37048235986, 80, 7.45916, 28.47);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Congo'), 57.67850113, 2439.35189403696, 80, 7.61597, 65.543);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Costa Rica'), 875.34973145, 11714.7105980732, 92, 59.763, 76.862);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Cote d''Ivoire'), 62.51667023, 1814.71855088017, 79, 38.44, 49.444);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Croatia'), 796.0, 12285.3032582105, 94, 69.845, 56.155);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Cuba'), 985.41900635, 7727.91997207998, 99, 37.3051, 76.896);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Cyprus'), 1596.0, 23487.228515625, 96, 71.7157, 66.946);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Czech Republic'), 1314.83728027, 17931.5987670768, 97, 75.6688, 73.477);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Democratic Republic of the Congo'), 19.13417244, 467.9145805459, 70, 3.8, 42.74);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Denmark'), 5532.0, 53094.0133607574, 93, 96.3305, 87.526);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Djibouti'), 80.65351105, 2376.12554719873, 84, 22.9, 77.417);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Dominican Republic'), 322.94607544, 6819.93225155181, 85, 54.2158, 78.566);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Ecuador'), 466.23751831, 5976.1596805651, 78, 48.9404, 63.398);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Egypt'), 173.5194397, 3306.98159414141, 93, 37.8194, 42.785);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'El Salvador'), 329.44250488, 3790.34089108162, 94, 26.8026, 69.7);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Equatorial Guinea'), 229.11935425, 9068.91003238645, 40, 21.32, 70.616);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Eritrea'), 26.82466125, 0.0, 95, 1.08373, 38.206);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Estonia'), 1156.20275879, 17722.1557669523, 93, 88.4097, 68.416);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Eswatini'), 252.67782593, 3393.53367834668, 90, 25.643, 23.3);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Ethiopia'), 23.53430557, 621.845673808133, 63, 13.8552, 19.428);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Fiji'), 169.72981262, 5097.53108832569, 99, 42.5, 54.726);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Finland'), 4128.0, 42560.3456767103, 97, 86.4221, 85.225);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'France'), 4201.78173828, 36702.432373337906, 97, 78.006, 79.655);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Gabon'), 188.42417908, 7047.12654634355, 80, 45.7845, 88.118);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Gambia'), 19.42744446, 619.536364296461, 97, 17.6, 59.228);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Georgia'), 294.0, 4086.6223465965, 94, 47.5698, 57.448);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Germany'), 4627.35791016, 41911.0109851054, 93, 87.5898, 77.2);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Ghana'), 77.74266815, 1721.69964380717, 88, 23.0, 54.086);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Greece'), 1481.41967773, 17980.7298238137, 99, 66.835, 78.046);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Grenada'), 389.39382935, 8694.12438005692, 92, 52.5, 35.997);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Guatemala'), 233.41566467, 3893.5052184813103, 70, 28.8059, 49.971);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Guinea'), 43.94221497, 747.356966759448, 47, 9.2, 35.141);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Guinea-Bissau'), 52.38645935, 645.066837207039, 86, 6.1, 42.123);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Guyana'), 228.02095032, 5640.41560569466, 95, 34.0, 26.441);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Haiti'), 68.24273682, 1411.12684746796, 64, 14.2, 52.427);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Honduras'), 168.92593384, 2271.20265980349, 98, 27.1395, 55.165);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Hungary'), 871.0, 12717.038597002, 99, 72.8347, 70.5);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Iceland'), 4270.0, 52951.6815110898, 92, 98.2, 93.7);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'India'), 58.0, 1583.99815907985, 87, 14.9, 32.777);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Indonesia'), 97.16175842, 3288.22269737572, 84, 22.0627, 53.313);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Iran'), 384.25985718, 4952.73355532178, 98, 45.335, 73.358);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Iraq'), 148.30059814, 4440.14189252367, 68, 15.2, 69.921);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Ireland'), 4575.94482422, 64311.823468405695, 95, 83.4948, 62.538);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Israel'), 2661.0, 36123.9907881129, 95, 77.3521, 92.179);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Italy'), 2676.0, 30387.1293187854, 93, 58.1417, 69.565);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Jamaica'), 285.59729004, 5062.89556466908, 91, 42.2212, 54.833);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Japan'), 3755.0, 34960.6393843385, 96, 91.058, 91.381);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Jordan'), 303.23452759, 4042.75678097555, 99, 54.22, 90.256);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Kazakhstan'), 314.0, 10196.1226255982, 98, 70.8299, 57.191);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Kenya'), 71.3065033, 1489.11959777284, 89, 16.5879, 25.658);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Kiribati'), 118.0, 1639.85274301496, 78, 14.9, 51.619);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Kuwait'), 1235.61889648, 29882.2126867068, 99, 82.0, 100.0);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Kyrgyz Republic'), 81.0, 1105.65202996955, 97, 30.247, 35.777);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Laos'), 52.15144348, 2121.01339097363, 83, 18.2, 33.108);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Latvia'), 776.0, 13321.9753140616, 94, 79.2006, 67.98);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Lebanon'), 578.64581299, 7714.1099998804, 82, 74.0, 88.106);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Lesotho'), 104.40470886, 1121.19851342518, 83, 25.0, 26.908);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Liberia'), 70.18363953, 692.590082351257, 65, 10.0, 49.82);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Libya'), 0.0, 7458.48917756374, 97, 0.0, 79.27);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Lithuania'), 920.0, 14300.2553666736, 93, 71.3781, 67.23);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Luxembourg'), 5422.0, 105462.012584423, 99, 96.3767, 90.179);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Madagascar'), 22.81040573, 445.320069480568, 62, 4.17397, 35.193);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Malawi'), 35.27587891, 539.605363240686, 88, 6.0, 16.313);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Malaysia'), 370.71954346, 9648.6797937523, 99, 71.0641, 74.213);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Maldives'), 823.0, 9644.90655028145, 99, 54.462, 38.529);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Mali'), 29.7465477, 704.821646439506, 71, 10.33, 39.991);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Malta'), 2243.0, 25481.8977555627, 97, 75.96, 94.414);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Mauritania'), 57.40904617, 1554.94897871782, 73, 17.6, 51.089);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Mauritius'), 515.37243652, 9507.87133656424, 97, 50.1393, 41.0);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Mexico'), 558.1651001, 10021.2386118827, 87, 57.431, 79.285);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Micronesia, Fed. Sts.'), 359.78536987, 2911.16211045292, 72, 31.5011, 22.456);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Moldova'), 186.0, 2749.55137054338, 87, 69.0, 42.49);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Mongolia'), 165.84915161, 3838.92126989984, 99, 22.5, 68.23);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Montenegro'), 577.0, 6517.19267514764, 89, 68.1198, 65.806);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Morocco'), 162.5098114, 3146.24780273438, 99, 57.08, 60.809);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Mozambique'), 39.91206741, 610.563774706589, 85, 6.5, 34.4);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Myanmar'), 63.0, 1166.73305546288, 89, 10.9, 29.858);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Namibia'), 495.62979126, 4774.10650865775, 92, 25.6879, 46.9);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Nepal'), 47.0, 875.543635474862, 91, 17.5816, 18.557);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Netherlands'), 4677.0, 45793.8135434697, 95, 91.7241, 90.173);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'New Zealand'), 3600.95629883, 38639.3501941427, 92, 85.2, 86.341);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Nicaragua'), 161.27700806, 2074.45446460028, 98, 19.7043, 57.895);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Niger'), 25.72568893, 485.662574175279, 84, 2.47622, 16.247);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Nigeria'), 96.28328705, 2585.73360671797, 42, 22.5, 47.838);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'North Korea'), 0.0, 0.0, 96, 0.0, 61.277);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'North Macedonia'), 303.0, 5262.68671928674, 91, 70.3802, 57.408);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Norway'), 7566.0, 74809.9658049898, 95, 96.8103, 81.091);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Oman'), 765.78533936, 18808.3077921839, 99, 73.53, 81.35);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Pakistan'), 35.0121994, 1380.47020838317, 72, 11.0, 36.026);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Palau'), 1809.50012207, 15690.7586522228, 90, 0.0, 78.159);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Palestine'), 0.0, 3272.15432360708, 99, 56.7, 75.368);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Panama'), 982.79394531, 14082.6548502728, 73, 51.2054, 66.696);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Papua New Guinea'), 45.50782776, 2484.5963398603, 49, 7.9, 13.012);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Paraguay'), 392.22418213, 5879.33792308671, 92, 49.7163, 60.75);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Peru'), 310.26644897, 6231.71150338894, 90, 40.8526, 77.357);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Philippines'), 116.0, 2909.85818014474, 74, 36.9, 46.284);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Poland'), 804.0, 12637.5220324406, 98, 67.997, 60.278);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Portugal'), 1791.0, 19215.7813014347, 98, 68.6329, 63.514);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Qatar'), 2435.44506836, 68985.2946961507, 99, 92.8848, 98.945);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Romania'), 442.0, 8977.01748158197, 89, 55.7632, 53.887);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Russia'), 499.0, 9277.7138671875, 97, 70.0992, 74.05);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Rwanda'), 48.80509567, 733.998585018273, 98, 12.5, 17.004);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Samoa'), 238.09069824, 4084.3608381993295, 80, 25.407, 18.914);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Sao Tome and Principe'), 84.50744629, 1298.10946596396, 96, 25.82, 70.174);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Saudi Arabia'), 1198.33630371, 22453.571552265, 98, 69.6162, 83.18);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Senegal'), 54.20389557, 1218.00613555438, 89, 21.7, 45.862);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Serbia'), 491.25177002, 5820.3215576888, 95, 65.317, 55.696);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Seychelles'), 623.9987793, 15333.1051727105, 97, 54.2596, 55.4);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Sierra Leone'), 114.16482544, 945.148168480629, 86, 6.34442, 40.829);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Singapore'), 2279.01708984, 55645.6068614606, 96, 79.013, 100.0);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Slovakia'), 1109.0, 16442.0760860018, 96, 77.6347, 53.889);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Slovenia'), 1776.0, 20697.2748530619, 95, 73.0987, 53.781);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Solomon Islands'), 94.91165924, 2045.47889485251, 87, 10.0005, 22.36);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Somalia'), 0.0, 445.583078625015, 42, 1.76, 43.245);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'South Africa'), 499.36334229, 6112.27382485974, 85, 51.9191, 64.828);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'South Korea'), 1894.34753418, 28737.4391706499, 98, 89.8963, 81.634);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'South Sudan'), 0.0, 1080.14718624765, 46, 3.0, 18.852);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Spain'), 2349.09375, 25969.8383138327, 97, 78.6896, 79.602);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Sri Lanka'), 147.0, 4060.13139670248, 99, 15.26, 18.256);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'St. Lucia'), 464.57443237, 10334.9225558425, 99, 57.3, 18.515);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'St. Vincent and the Grenadines'), 303.9425354, 7353.73556054184, 99, 49.4, 50.964);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Sudan'), 98.24565125, 1292.37963867188, 93, 0.0, 33.894);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Suriname'), 517.38494873, 8813.61705392067, 73, 42.7638, 66.056);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Sweden'), 5599.0, 51197.9529341175, 98, 90.6102, 86.553);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Switzerland'), 9082.45019531, 83806.4476003837, 96, 87.4791, 73.718);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Syria'), 0.0, 847.731631942565, 54, 29.9798, 52.168);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Tajikistan'), 64.0, 956.916310930656, 96, 18.98, 26.742);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Tanzania'), 32.90985107, 939.127319335938, 96, 10.0, 31.617);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Thailand'), 219.91911316, 5688.85335397884, 99, 39.3161, 47.694);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Timor-Leste'), 101.42063141, 1319.59297370991, 76, 18.6, 29.49);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Togo'), 37.41205215, 751.052405084336, 82, 7.12, 40.1);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Tonga'), 169.94888306, 4123.90323993332, 96, 38.6513, 23.275);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Trinidad and Tobago'), 1039.05749512, 20024.754663902, 96, 65.1, 53.319);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Tunisia'), 246.10754395, 4014.94773686432, 98, 46.5, 68.056);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Turkiye'), 447.0, 11049.9951100942, 97, 53.745, 73.611);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Turkmenistan'), 390.99450684, 5759.497903834, 99, 14.9968, 50.317);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Uganda'), 40.15630341, 862.934610355811, 89, 5.8, 22.06);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Ukraine'), 158.0, 2094.47387695313, 23, 48.8846, 69.061);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'United Arab Emirates'), 1439.30053711, 43534.9972681733, 99, 90.5, 85.674);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'United Kingdom'), 4433.85839844, 44964.3911437292, 95, 92.0003, 82.626);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'United States'), 9248.93457031, 57040.2082136605, 95, 74.5542, 81.671);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Uruguay'), 1410.3215332, 17125.9016800298, 95, 64.5708, 95.045);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Uzbekistan'), 132.0, 2803.19018021751, 99, 42.8, 50.75);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Vanuatu'), 114.26020813, 2746.59171880997, 80, 22.3514, 24.961);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Venezuela'), 0.0, 0.0, 87, 58.0, 88.154);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Vietnam'), 122.27213287, 2577.56885340113, 97, 45.0, 33.809);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Yemen'), 63.30020905, 1362.17379435676, 63, 24.0854, 34.777);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Zambia'), 57.92047501, 1295.87788680068, 90, 8.8, 41.907);
INSERT INTO World_Bank_Data (country_id, health_expenditure, gdp_per_capita, immunization_rate, internet_usage, urban_population) VALUES ((SELECT country_id FROM Countries WHERE name = 'Zimbabwe'), 105.09803009, 1386.42284717709, 87, 22.7428, 32.385);
